package com.cnpm.model;
// Generated Aug 14, 2020 1:39:30 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "booking", catalog = "onlinehotel")
public class Booking implements java.io.Serializable {

	private Integer id;
	private Room room;
	private Date checkInt;
	private Date checkOut;
	private int total;

	public Booking() {
	}

	public Booking(Room room, Date checkInt, Date checkOut, int total) {
		this.room = room;
		this.checkInt = checkInt;
		this.checkOut = checkOut;
		this.total = total;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_id", nullable = false)
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "check_int", nullable = false, length = 10)
	public Date getCheckInt() {
		return this.checkInt;
	}

	public void setCheckInt(Date checkInt) {
		this.checkInt = checkInt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "check_out", nullable = false, length = 10)
	public Date getCheckOut() {
		return this.checkOut;
	}

	public void setCheckOut(Date checkOut) {
		this.checkOut = checkOut;
	}

	@Column(name = "total", nullable = false)
	public int getTotal() {
		return this.total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

}
